travis:
  secure:
    BINSTAR_TOKEN: JP0JB2TV4ND0Y8vN4zLcgG7QTVOrAjY/NqZU6CqFyz0mjYqA/gk5j66jOW6+8/aR4rzRvpgYIbqjwzbeRphcHDgPO/5tY5FgAqO+X7yFLn+ylsFQ9880t+pTxKIRCKaNnAuuzrMdY21JsmgnZygTRRU6uMnwZ+7+BhbsMtKZ1B6nErh93joTN/Z6jnueqD2tbn1WJCH1t4eEGWgr26v7549q6Spm8XobmW045i0jGjoV8TRTs/HQqFbIKvtU4Iz4l1qrFz6va7a0zn6hiYjqioLznAqk+W3nuIh5ah84A1VR8SEmskPgAb7dPoPfdSNeCwQWstKf4VSrSdStHZTtkM/CoWwS+m6Abypwe+xheqoEIexWV1hDKxvs6tA056O0UwJpDkvXCX+ID0P15s+qN5jgWMOsTL34TDVO9iFpkHK/KGqvJXSfilGHSvwwct6XChRgLdQCKEUXxHUIM1Mf9GZbC/IRVTAKVdF0igs7RRS5lpDWkE0atJr9Yo5AtNG4cIEXGRPZY5ohjECf6Z2gOEI/XO5/rPKsVKMEi+4tz4g4tygY23pZ8o/DjTVLBwN4H8hVwWWd1+4wKCPyTvXCL8xAwAnY8jiHSsIbUBl7g16Uxdto/SKLpL488UwvMe1i9DqLaUiftYPM3EwF1tOZhi1i495l2ZxjUbJE5VVdvpA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  linux: azure
  osx: azure
  win: azure
conda_forge_output_validation: true
